version: 2

models:
  - name: int_page_views
    description: Distinct page views
    columns:
      - name: session_id
        tests:
          - not_null
          - unique
      - name: first_event
      - name: last_event

  - name: int_session_length
    description: First and last events
    columns:
      - name: session_id
        tests:
          - not_null
          - unique
      - name: first_event
      - name: last_event

  - name: int_session_events_agg
    description: Session event aggregation to count events
    columns:
      - name: session_id
        tests:
          - not_null
          - unique
      - name: created_at_utc
      - name: user_id
      - name: page_url
      - name: page_view
      - name: checkout
      - name: add_to_cart
      - name: package_shipped
